"""Add updated column

Revision ID: 1a2f7e2c4cb7
Revises: c134bb6db8b2
Create Date: 2024-11-26 15:51:23.021790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2f7e2c4cb7'
down_revision = 'c134bb6db8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
