"""Initial migration

Revision ID: d10b22a60ee8
Revises: 
Create Date: 2024-11-18 17:20:29.837313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10b22a60ee8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('schedule_time', sa.String(length=50), nullable=True))
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.drop_column('schedule_time')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
